[base16]
  base00 = "#1d1c1c"
  base01 = "#272626"
  base02 = "#2b2b2b"
  base03 = "#363636"
  base04 = "#525252"
  base05 = "#dddddd"
  base06 = "#e6e1cf"
  base07 = "#d9d7ce"
  base08 = "#e95678"
  base09 = "#fbc3a7"
  base0a = "#25b0bc"
  base0b = "#fab795"
  base0c = "#59e1e3"
  base0d = "#3fc4de"
  base0e = "#b877db"
  base0f = "#f09483"

[pager]
  heading = "#ee64ac"

[code]
  pink = "#ee64ac"
